### ISSUE TITLE
Support for `SDJWTClaimsStrategy::No` 

### ISSUE THREAD

**Issue by whalelephant** [openwallet-foundation-labs/sd-jwt-rust#17]
Hi, 

Just going through the code I was wondering if there is specific reason that the claim strategy for `No` is currently not supported for the compact format?
 
Specifically referring to the [`parse_sd_jwt`](https://github.com/openwallet-foundation-labs/sd-jwt-rust/blob/b99ffbee5326bd23743fdd6533a9d58d50c04f11/src/lib.rs#L121) function. 

Thanks!

**Comment by jovfer** [comment]
Hi @whalelephant, thank you for the report. There is no particular reason, just an implementation error.

**Comment by jovfer** [comment]
Just for a reference, a quote from https://www.ietf.org/archive/id/draft-ietf-oauth-selective-disclosure-jwt-07.html#section-5:
```
An SD-JWT without Disclosures and without a KB-JWT:
<Issuer-signed JWT>~

An SD-JWT without Disclosures and with a KB-JWT:
<Issuer-signed JWT>~<KB-JWT>

An SD-JWT with Disclosures and without a KB-JWT:
<Issuer-signed JWT>~<Disclosure 1>~<Disclosure N>~

An SD-JWT with Disclosures and with a KB-JWT:
<Issuer-signed JWT>~<Disclosure 1>~<Disclosure N>~<KB-JWT>
```

**Comment by whalelephant** [comment]
@jovfer thank you for your response, understood. 

I am still very new to sd-jwt so once I have gone through the code more will revert perhaps to address this.

**Comment by jovfer** [comment]
@whalelephant ok, FYI, we are going to fix this particular issue this week
